apiVersion: apps/v1
kind: Deployment
metadata:
  name: c5-project-imgproc
  labels:
    service: c5-project-imgproc
spec:
  replicas: 2
  selector:
    matchLabels:
      service: c5-project-imgproc
  template:
    metadata:
      labels:
        service: c5-project-imgproc
    spec:
      restartPolicy: Always
      volumes:
        - name: aws-secret
          secret:
            secretName: aws-secret
      containers:
      - name: c5-project-imgproc
        image: demellj/c5-project-imgproc:latest
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: env-config
        - secretRef:
            name: env-secret
        volumeMounts:
        - name: aws-secret
          mountPath: "/home/appuser/.aws/"
          readOnly: true
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
