apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
type: Opaque
data:
  credentials: 

---
apiVersion: v1
kind: Secret
metadata:
  name: env-secret
type: Opaque
data:
  POSTGRESS_USERNAME: 
  POSTGRESS_PASSWORD: 
  JWT_SECRET: 

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: env-config
data:
  AWS_REGION: 
  AWS_PROFILE: 
  AWS_MEDIA_BUCKET: 
  AWS_THUMBNAILS_BUCKET: 
  AWS_THUMBNAILS_BASE_URL: 
  AWS_SQS_QUEUE: 
  POSTGRESS_HOST: 
  POSTGRESS_DATABASE: 
  URL: 
