name: Build and Publish

on:
  push:
    tags: [ 'v*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build phase 1
      uses: isbang/compose-action@v1.0.0
      with:
        compose-file: './docker/docker-compose-build-phase1.yaml'

    - name: Build phase 2
      uses: isbang/compose-action@v1.0.0
      with:
        compose-file: './docker/docker-compose-build-phase2.yaml'

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    # Extract metadata (tags, labels) for Docker
    # https://github.com/docker/metadata-action
    - name: Extract feed-api metadata
      id: meta_feed
      uses: docker/metadata-action@v3
      with:
        images: demellj/c5-project-api-feed
        tags: |
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}

    - name: Extract user-api metadata
      id: meta_user
      uses: docker/metadata-action@v3
      with:
        images: demellj/c5-project-api-user
        tags: |
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}

    - name: Extract reverseproxy metadata
      id: meta_reverseproxy
      uses: docker/metadata-action@v3
      with:
        images: demellj/c5-project-reverseproxy
        tags: |
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}

    - name: Extract imgproc metadata
      id: meta_imgproc
      uses: docker/metadata-action@v3
      with:
        images: demellj/c5-project-imgproc
        tags: |
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}

    - name: Publish feed-api
      uses: belon/docker-build-push@v4.0
      with:
        image: demellj/c5-project-api-feed
        tags: ${{ join(steps.meta_feed.outputs.tags) }}
        registry: docker.io
        username: $${ secrets.DOCKER_USERNAME }}
        password: $${ secrets.DOCKER_TOKEN }}

    - name: Publish user-api
      uses: belon/docker-build-push@v4.0
      with:
        image: demellj/c5-project-api-user
        tags: ${{ join(steps.meta_user.outputs.tags) }}
        registry: docker.io
        username: $${ secrets.DOCKER_USERNAME }}
        password: $${ secrets.DOCKER_TOKEN }}

    - name: Publish reverseproxy
      uses: belon/docker-build-push@v4.0
      with:
        image: demellj/c5-project-reverseproxy
        tags: ${{ join(steps.meta_reverseproxy.outputs.tags) }}
        registry: docker.io
        username: $${ secrets.DOCKER_USERNAME }}
        password: $${ secrets.DOCKER_TOKEN }}

    - name: Publish imgproc
      uses: belon/docker-build-push@v4.0
      with:
        image: demellj/c5-project-imgproc
        tags: ${{ join(steps.meta_imgproc.outputs.tags) }}
        registry: docker.io
        username: $${ secrets.DOCKER_USERNAME }}
        password: $${ secrets.DOCKER_TOKEN }}
